name: Deploy to production site
on:
  push: # Detects when a push to the Repo is operated, and initiates

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }} # The IP address of the Wordpress Server
          key: ${{ secrets.KEY }} # The Private SSH Key for the server
          username: ${{ secrets.USERNAME }} # The username of the server (default is currently root)
          script: | # Operates script to pull the github repo to remote server
            cd /var/www/html/wp-content/themes
            git pull https://github.com/AdsyEdge/CP3402-U3A-AdamEdgar.git local
            echo 'Deployment to production site successful'