name: Deploy to production site
on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }} # The IP address of the Wordpress Server
        username: ${{ secrets.SSH_USER }} # The username of the server (default is root)
        key: ${{ secrets.SSH_KEY }} # The Private SSH Key for the server
        script: |
          git clone https://github.com/AdsyEdge/CP3402-U3A-AdamEdgar.git /test

        # cd ..
        # cd /var/www/html/wp-content/themes
        # git pull
          echo 'Deployment to production site successful'