name: Deploy to production site
on:
  push:
    branches: [local]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }} # The IP address of the Wordpress Server
          key: ${{ secrets.SSH_KEY }} # The Private SSH Key for the server
          username: ${{ secrets.SSH_USERNAME }} # The username of the server (default is root)
          script: |
            mkdir test
            cd test
            git clone https://github.com/AdsyEdge/CP3402-U3A-AdamEdgar.git

            # Additional commands
            # cd /var/www/html/wp-content/themes
            # git pull

            echo 'Deployment to production site successful'